//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by 餐饮管理系统.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MY_DIALOG                   102
#define IDR_MAINFRAME                   128
#define IDB_backGround                  131
#define IDI_ICON_total                  134
#define IDI_ICON_num                    134
#define IDI_ICON_add                    136
#define IDI_ICON_update                 136
#define IDI_ICON_login                  137
#define IDI_ICON_reg                    138
#define IDI_ICON_dayincome              139
#define IDI_ICON_cancel                 140
#define IDI_ICON_payorder               141
#define IDI_ICON_open                   142
#define IDI_ICON_founding               143
#define IDI_ICON_order                  144
#define IDR_MENU                        146
#define IDD_login                       149
#define IDB_loginImage                  151
#define IDD_openTable                   152
#define IDD_register                    153
#define IDD_selectDishes                154
#define IDD_dishesNum                   156
#define IDD_dishesTotle                 157
#define IDD_updateDishes                158
#define IDD_payorder                    159
#define IDD_buyGoods                    160
#define IDD_GoodsInfo                   161
#define IDD_dishesInfo                  162
#define IDD_monthIncome                 163
#define IDD_goodsSelect                 164
#define IDD_managePower                 165
#define IDD_userManage                  166
#define IDD_copySQL                     167
#define IDD_returnSQL                   168
#define IDD_cookermenu                  169
#define IDI_ICON_cookermenu             171
#define IDB_BITMAP1                     197
#define IDB_BITMAPxiangchisha           219
#define IDB_BITMAPbuygoods_exit1        220
#define IDB_BITMAPbuygoods_exit2        221
#define IDB_BITMAPbuygoods_right2       222
#define IDB_BITMAPbuygoods_ensure1      223
#define IDB_BITMAPbuygoods_ensure2      224
#define IDB_BITMAPbuygoods_left1        225
#define IDB_BITMAPbuygoods_left2        226
#define IDB_BITMAPbuygoods_reset1       227
#define IDB_BITMAPbuygoods_reset2       228
#define IDB_BITMAPbuygoods_right1       229
#define IDB_BITMAPcookermenu_fresh2     231
#define IDB_BITMAPcookermenu_clear1     232
#define IDB_BITMAPcookermenu_clear2     233
#define IDB_BITMAPcookermenu_delete1    234
#define IDB_BITMAPcookermenu_delete2    235
#define IDB_BITMAPcookermenu_fresh1     236
#define IDB_BITMAPdishinfo_update2      237
#define IDB_BITMAPdishinfo_add1         238
#define IDB_BITMAPdishinfo_add2         239
#define IDB_BITMAPdishinfo_back1        240
#define IDB_BITMAPdishinfo_back2        241
#define IDB_BITMAPdishinfo_delete1      242
#define IDB_BITMAPdishinfo_delete2      243
#define IDB_BITMAPdishinfo_update1      244
#define IDB_BITMAPgoodsselect_query2    249
#define IDB_BITMAPgoodsselect_cancel1   250
#define IDB_BITMAPgoodsselect_cancel2   251
#define IDB_BITMAPgoodsselect_query1    252
#define IDB_BITMAPlogin_cancel1         253
#define IDB_BITMAPlogin_cancel2         254
#define IDB_BITMAPlogin_login1          255
#define IDB_BITMAPlogin_login2          256
#define IDB_BITMAPmangepower_set1       257
#define IDB_BITMAPmangepower_set2       258
#define IDD_member                      259
#define IDB_BITMAPbackground            260
#define IDB_BITMAPmy_login2             261
#define IDB_BITMAPmy_change1            262
#define IDB_BITMAPmy_change2            263
#define IDB_BITMAPmy_count1             264
#define IDB_BITMAPmy_count2             265
#define IDB_BITMAPmy_eat1               266
#define IDB_BITMAPmy_eat2               267
#define IDB_BITMAPmy_employ1            268
#define IDB_BITMAPmy_employ2            269
#define IDB_BITMAPmy_exit1              270
#define IDB_BITMAPmy_exit2              271
#define IDB_BITMAPmy_login1             272
#define IDB_BITMAPmonthincome_enquery2  283
#define IDB_BITMAPmonthincome_cancel1   284
#define IDB_BITMAPmonthincome_cancel2   285
#define IDB_BITMAPmonthincome_enquery1  286
#define IDB_BITMAPot_back2              287
#define IDB_BITMAPot_select1            288
#define IDB_BITMAPot_select2            289
#define IDB_BITMAPot_back1              290
#define IDB_BITMAPpay_member1           291
#define IDB_BITMAPpay_member2           292
#define IDB_BITMAPpay_OK1               293
#define IDB_BITMAPpay_OK2               294
#define IDB_BITMAPregister_register2    295
#define IDB_BITMAPregister_cancel1      296
#define IDB_BITMAPregister_cancel2      297
#define IDB_BITMAPregister_register1    298
#define IDB_BITMAPrs_r2                 299
#define IDB_BITMAPrs_browse1            300
#define IDB_BITMAPrs_browse2            301
#define IDB_BITMAPrs_cancel1            302
#define IDB_BITMAPrs_cancel2            303
#define IDB_BITMAPrs_r1                 304
#define IDB_BITMAPsd_OK1                325
#define IDB_BITMAPsd_OK2                326
#define IDB_BITMAPsd_pay1               327
#define IDB_BITMAPsd_pay2               328
#define IDB_BITMAPsd_select1            329
#define IDB_BITMAPsd_select2            330
#define IDB_BITMAPsd_cancel1            331
#define IDB_BITMAPsd_cancel2            332
#define IDB_BITMAPsd_cancelb1           333
#define IDB_BITMAPsd_cancelb2           334
#define IDB_BITMAPuseramanage_cancel2   335
#define IDB_BITMAPusermanage_cancel1    336
#define IDB_BITMAPusermanage_delete1    337
#define IDB_BITMAPusermanage_delete2    338
#define IDB_BITMAPusermanage_update1    339
#define IDB_BITMAPusermanage_update2    340
#define IDI_ICON1                       342
#define IDB_BITMAP2                     343
#define IDC_username                    1000
#define IDC_userpwd                     1001
#define IDC_btnOK                       1002
#define IDC_btnCancel                   1003
#define IDC_listShow                    1003
#define IDC_tableID                     1004
#define IDC_Cancel                      1004
#define IDC_btnSelectTable              1005
#define IDC_btnBack                     1006
#define IDC_userPasswnd                 1007
#define IDC_reapetPwd                   1008
#define IDC_btnRegister                 1009
#define IDC_bntCancel                   1010
#define IDC_tablesID                    1010
#define IDC_listShowDishes              1011
#define IDC_btnSelect                   1012
#define IDC_listSelect                  1013
#define IDC_dishesNum                   1018
#define IDC_listShowSelect              1022
#define IDC_bntADD                      1023
#define IDC_bntSUB                      1024
#define IDC_bntUpdate                   1024
#define IDC_bntOK                       1025
#define IDC_bntDelete                   1025
#define IDC_payOrder                    1029
#define IDC_receiver                    1030
#define IDC_surplus                     1031
#define IDC_receiver2                   1032
#define IDC_discount                    1032
#define IDC_listShowOrder               1033
#define IDC_receiver3                   1034
#define IDC_afterdiscount               1034
#define IDC_listShowGoods               1035
#define IDC_buyTime                     1036
#define IDC_goodsAdd                    1038
#define IDC_goodsSub                    1039
#define IDC_goodsNum                    1040
#define IDC_totlePrice                  1041
#define IDC_bntReset                    1043
#define IDC_goodsName                   1043
#define IDC_goodsPrice                  1044
#define IDC_dishesPrice                 1049
#define IDC_dishesName                  1051
#define IDC_incomeYear                  1052
#define IDC_incomeMonth                 1053
#define IDC_bntFound                    1054
#define IDC_stockYear                   1055
#define IDC_stockMonth                  1056
#define IDC_stockDay                    1057
#define IDC_bntQuery                    1059
#define IDC_manager                     1061
#define IDC_forman                      1062
#define IDC_assistant                   1063
#define IDC_listShowInfo                1067
#define IDC_copyWay                     1071
#define IDC_browse                      1072
#define IDC_DatabaseName                1073
#define IDC_databasePath                1075
#define IDC_bntCheck                    1076
#define IDC_bntReturn                   1077
#define IDC_CUSTOM1                     1081
#define IDC_listcookerdishes            1082
#define IDC_cookerdeletedishes          1085
#define IDC_cookerdeletealldishes       1086
#define IDC_updatecookermenu            1087
#define IDC_cooker                      1088
#define IDC_BUTTON1                     1103
#define IDR_MENU_exit                   1104
#define IDC_background                  1105
#define IDC_COMBOmemberID               1106
#define IDC_member                      1107
#define IDC_festivallist                1108
#define IDC_COMBO1                      1109
#define IDC_RADIO1                      1110
#define IDC_RADIO2                      1111
#define IDC_RADIO3                      1112
#define IDR_MENU_open                   32772
#define IDR_MENU_update                 32773
#define IDR_MENU_pay                    32774
#define IDR_MENU_dayincome              32775
#define IDR_MENU_buygoods               32776
#define IDR_MENU_employeesManage        32777
#define IDR_MENU_goodsInfo              32778
#define IDR_MENU_dishesInfo             32779
#define IDR_MENU_monthIncome            32780
#define IDR_MENU_googsSelect            32781
#define IDR_MENU_goodsSelect            32781
#define IDR_MENU_copySQL                32782
#define IDR_MENU_returnSQL              32783
#define IDR_MENU_newSQL                 32784
#define IDR_MENU_power                  32785
#define IDR_MENU_about                  32786
#define IDR_MENU_login                  32787
#define IDR_MEUNselectAccess            32788
#define IDR_MENUsql2005                 32789
#define IDR_MENU_cookermenu             32790
#define IDR_MENU_register               32792
#define IDR_menu_member                 32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        346
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
